# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - name: Insatall NPM modules
      run: npm install 
      #npm ci se vzimat ne ot package.json a ot *.log file
    - name: Start Backend 
      run: npm run start-be &
    - name: Start Frontend
      run: npm run start-fe &
    - name: Install Playwright
      run: npx playwright install
    - name: Run UI tests
      run: npm run tets:ui
